sonar.projectKey=healthsecure-platform
sonar.projectName=HealthSecure Platform
sonar.projectVersion=1.0

sonar.sources=app/backend/app
sonar.tests=app/backend/tests
sonar.python.version=3.13

sonar.sourceEncoding=UTF-8
