version: "3.9"

services:

  backend:
    build: .
    container_name: healthsecure-backend

    ports:
      - "8000:8000"

    depends_on:
      - postgres
      - redis

    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: healthsecure
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres

      REDIS_HOST: redis
      REDIS_PORT: 6379

  postgres:
    image: postgres:16

    container_name: healthsecure-postgres

    environment:
      POSTGRES_DB: healthsecure
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

    container_name: healthsecure-redis

    ports:
      - "6379:6379"

volumes:

  postgres_data:
